function dydx = cartpole_odefun2(ddsdswitch,ddthetadswitch,dp1dswitch,dp2dswitch,ds,dtheta,dthetadswitch,p1,p2,tfin,theta,tswitch,wp)
%CARTPOLE_ODEFUN2
%    DYDX = CARTPOLE_ODEFUN2(DDSDSWITCH,DDTHETADSWITCH,DP1DSWITCH,DP2DSWITCH,DS,DTHETA,DTHETADSWITCH,P1,P2,TFIN,THETA,TSWITCH,WP)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    18-Jun-2018 16:25:26

t2 = tfin-tswitch;
dydx = [ds.*t2;dtheta.*t2;0.0;0.0;0.0;-t2.*theta.*wp;-p1.*t2;-p2.*t2;-ds+ddsdswitch.*t2;-dtheta+ddthetadswitch.*t2;0.0;0.0;0.0;theta.*wp-dthetadswitch.*t2.*wp;p1-dp1dswitch.*t2;p2-dp2dswitch.*t2];
